version: '3'

services:
  app:
    image: app:latest
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - celery_worker
    environment:
        DB_USERNAME: admin
        DB_PASSWORD: admin
        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: avito-test
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_CACHE_DB: 0
        REDIS_CELERY_DB: 1
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: avito-test
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  celery_worker:
    build: .
    command: ["celery", "-A", "services.celery_tasks.celery", "worker", "--loglevel=info", "-P", "eventlet"]
    depends_on:
      - postgres
      - redis
    networks:
      - mynetwork
    environment:
        DB_USERNAME: admin
        DB_PASSWORD: admin
        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: avito-test
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_CACHE_DB: 0
        REDIS_CELERY_DB: 1

networks:
  mynetwork:
    driver: bridge